"""reports

Revision ID: 12420769c5a4
Revises: e8b8d83ca9d0
Create Date: 2026-09-24 03:15:48.845952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12420769c5a4'
down_revision = 'e8b8d83ca9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_format', sa.Enum('pdf', 'docx', name='report_format', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.session_id'], name=op.f('fk_reports_session_id_analysis_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_reports_user_id_users')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_session_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
