"""document parsing fields

Revision ID: 26c538cfb329
Revises: 30fcec4b01cf
Create Date: 2026-09-24 02:12:26.760460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c538cfb329'
down_revision = '30fcec4b01cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_documents_content_hash'), ['content_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_documents_content_hash'), type_='unique')
        batch_op.drop_column('page_count')
        batch_op.drop_column('word_count')
        batch_op.drop_column('extracted_text')
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
