"""session heartbeat

Revision ID: 49eb1962fdba
Revises: 12420769c5a4
Create Date: 2026-09-24 03:59:38.756882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49eb1962fdba'
down_revision = '12420769c5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.drop_column('heartbeat_at')

    # ### end Alembic commands ###
