"""recommendation rank and evidence

Revision ID: e8b8d83ca9d0
Revises: 5dc5d3148a7f
Create Date: 2026-09-24 03:02:01.936108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b8d83ca9d0'
down_revision = '5dc5d3148a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('evidence')
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
